# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from planner_msgs/PlannerLogger.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class PlannerLogger(genpy.Message):
  _md5sum = "b8d38f1917746aa79f659b85baf83236"
  _type = "planner_msgs/PlannerLogger"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

float32 graph_build_time
float32 exp_gain_time
float32 total_time
float32 path_length

float32 find_frontier
float32 time_search_path_to_frontier

float32 map_resolution
int32 number_free_voxels
int32 number_occupied_voxels
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','graph_build_time','exp_gain_time','total_time','path_length','find_frontier','time_search_path_to_frontier','map_resolution','number_free_voxels','number_occupied_voxels']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','float32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,graph_build_time,exp_gain_time,total_time,path_length,find_frontier,time_search_path_to_frontier,map_resolution,number_free_voxels,number_occupied_voxels

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlannerLogger, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.graph_build_time is None:
        self.graph_build_time = 0.
      if self.exp_gain_time is None:
        self.exp_gain_time = 0.
      if self.total_time is None:
        self.total_time = 0.
      if self.path_length is None:
        self.path_length = 0.
      if self.find_frontier is None:
        self.find_frontier = 0.
      if self.time_search_path_to_frontier is None:
        self.time_search_path_to_frontier = 0.
      if self.map_resolution is None:
        self.map_resolution = 0.
      if self.number_free_voxels is None:
        self.number_free_voxels = 0
      if self.number_occupied_voxels is None:
        self.number_occupied_voxels = 0
    else:
      self.header = std_msgs.msg.Header()
      self.graph_build_time = 0.
      self.exp_gain_time = 0.
      self.total_time = 0.
      self.path_length = 0.
      self.find_frontier = 0.
      self.time_search_path_to_frontier = 0.
      self.map_resolution = 0.
      self.number_free_voxels = 0
      self.number_occupied_voxels = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7f2i().pack(_x.graph_build_time, _x.exp_gain_time, _x.total_time, _x.path_length, _x.find_frontier, _x.time_search_path_to_frontier, _x.map_resolution, _x.number_free_voxels, _x.number_occupied_voxels))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.graph_build_time, _x.exp_gain_time, _x.total_time, _x.path_length, _x.find_frontier, _x.time_search_path_to_frontier, _x.map_resolution, _x.number_free_voxels, _x.number_occupied_voxels,) = _get_struct_7f2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7f2i().pack(_x.graph_build_time, _x.exp_gain_time, _x.total_time, _x.path_length, _x.find_frontier, _x.time_search_path_to_frontier, _x.map_resolution, _x.number_free_voxels, _x.number_occupied_voxels))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.graph_build_time, _x.exp_gain_time, _x.total_time, _x.path_length, _x.find_frontier, _x.time_search_path_to_frontier, _x.map_resolution, _x.number_free_voxels, _x.number_occupied_voxels,) = _get_struct_7f2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7f2i = None
def _get_struct_7f2i():
    global _struct_7f2i
    if _struct_7f2i is None:
        _struct_7f2i = struct.Struct("<7f2i")
    return _struct_7f2i
